services:
  - type: web
    name: logintel-ai
    runtime: docker
    dockerfilePath: ./laravel/Dockerfile
    branch: main
    envVars:
      - key: APP_NAME
        value: LogIntel.AI
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
